#pragma once

#define HAL_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_RCC_MODULE_ENABLED
#define HAL_PWR_MODULE_ENABLED
#define HAL_CORTEX_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
#define HAL_FLASH_MODULE_ENABLED
#define HAL_I2C_MODULE_ENABLED
#define HAL_SPI_MODULE_ENABLED
#define HAL_SAI_MODULE_ENABLED
#define HAL_SD_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED
#define HAL_TIM_MODULE_ENABLED
#define HAL_EXTI_MODULE_ENABLED
#define HAL_RCC_EX_MODULE_ENABLED
#define HAL_FLASH_EX_MODULE_ENABLED
#define HAL_PWR_EX_MODULE_ENABLED
#define HAL_I2C_EX_MODULE_ENABLED
#define HAL_SPI_EX_MODULE_ENABLED
#define HAL_SAI_EX_MODULE_ENABLED
#define HAL_TIM_EX_MODULE_ENABLED
#define HAL_SDMMC_MODULE_ENABLED
#define HAL_SDMMC_EX_MODULE_ENABLED

#define HSE_VALUE    8000000U
#define HSE_STARTUP_TIMEOUT  100U
#define LSE_VALUE    32768U
#define LSE_STARTUP_TIMEOUT  5000U
#define CSI_VALUE    4000000U
#define HSI_VALUE    64000000U

#define TICK_INT_PRIORITY  0x0FU
#define PREFETCH_ENABLE    1U
#define ART_ACCELERATOR_ENABLE    1U
#define USE_HAL_DRIVER

#include "stm32h7xx_hal.h"
