; MP3 Player Firmware
; MCU: STM32H743VIT6 (Cortex-M7, 480MHz, 2MB Flash, 1MB RAM)

[env:stm32h743]
platform = ststm32
board = devebox_h743vitx
framework = stm32cube

build_flags =
    -DSTM32H743xx
    -DUSE_HAL_DRIVER
    -DHSE_VALUE=8000000
    -DLSE_VALUE=32768
    -Wno-missing-field-initializers

build_unflags = -std=gnu++14
build_src_flags = -std=gnu++17 -Wno-register -Wno-vla
